# ifndef PREPROCESSOR_SEQ_FOR_EACH_PRODUCT_HPP
# define PREPROCESSOR_SEQ_FOR_EACH_PRODUCT_HPP
#
# include <takisy/preprocessor/arithmetic/dec.hpp>
# include <takisy/preprocessor/config/config.hpp>
# include <takisy/preprocessor/control/if.hpp>
# include <takisy/preprocessor/repetition/for.hpp>
# include <takisy/preprocessor/seq/seq.hpp>
# include <takisy/preprocessor/seq/size.hpp>
# include <takisy/preprocessor/tuple/elem.hpp>
# include <takisy/preprocessor/tuple/rem.hpp>
#
# /* PP_SEQ_FOR_EACH_PRODUCT */
#
# define PP_SEQ_FOR_EACH_PRODUCT(macro, sets) PP_SEQ_FOR_EACH_PRODUCT_E(PP_FOR, macro, sets)
#
# /* PP_SEQ_FOR_EACH_PRODUCT_R */
#
# define PP_SEQ_FOR_EACH_PRODUCT_R(r, macro, sets) PP_SEQ_FOR_EACH_PRODUCT_E(PP_FOR_ ## r, macro, sets)
#
# if ~PP_CONFIG_FLAGS() & PP_CONFIG_EDG()
#    define PP_SEQ_FOR_EACH_PRODUCT_E(impl, macro, sets) impl((PP_SEQ_HEAD(sets)(nil), PP_SEQ_TAIL(sets)(nil), (nil), macro), PP_SEQ_FOR_EACH_PRODUCT_P, PP_SEQ_FOR_EACH_PRODUCT_O, PP_SEQ_FOR_EACH_PRODUCT_M_0)
# else
#    define PP_SEQ_FOR_EACH_PRODUCT_E(impl, macro, sets) PP_SEQ_FOR_EACH_PRODUCT_E_I(impl, macro, sets)
#    define PP_SEQ_FOR_EACH_PRODUCT_E_I(impl, macro, sets) impl((PP_SEQ_HEAD(sets)(nil), PP_SEQ_TAIL(sets)(nil), (nil), macro), PP_SEQ_FOR_EACH_PRODUCT_P, PP_SEQ_FOR_EACH_PRODUCT_O, PP_SEQ_FOR_EACH_PRODUCT_M_0)
# endif
#
# if PP_CONFIG_FLAGS() & PP_CONFIG_STRICT()
#    define PP_SEQ_FOR_EACH_PRODUCT_P(r, data) PP_SEQ_FOR_EACH_PRODUCT_P_I data
#    define PP_SEQ_FOR_EACH_PRODUCT_P_I(cset, rset, res, macro) PP_DEC(PP_SEQ_SIZE(cset))
# else
#    define PP_SEQ_FOR_EACH_PRODUCT_P(r, data) PP_DEC(PP_SEQ_SIZE(PP_TUPLE_ELEM(4, 0, data)))
# endif
#
# if ~PP_CONFIG_FLAGS() & PP_CONFIG_MWCC()
#    define PP_SEQ_FOR_EACH_PRODUCT_O(r, data) PP_SEQ_FOR_EACH_PRODUCT_O_I data
#    define PP_SEQ_FOR_EACH_PRODUCT_O_I(cset, rset, res, macro) (PP_SEQ_TAIL(cset), rset, res, macro)
# else
#    define PP_SEQ_FOR_EACH_PRODUCT_O(r, data) (PP_SEQ_TAIL(PP_TUPLE_ELEM(4, 0, data)), PP_TUPLE_ELEM(4, 1, data), PP_TUPLE_ELEM(4, 2, data), PP_TUPLE_ELEM(4, 3, data))
# endif
#
# define PP_SEQ_FOR_EACH_PRODUCT_C(data, i) PP_IF(PP_DEC(PP_SEQ_SIZE(PP_TUPLE_ELEM(4, 1, data))), PP_SEQ_FOR_EACH_PRODUCT_N_ ## i, PP_SEQ_FOR_EACH_PRODUCT_I)
#
# if ~PP_CONFIG_FLAGS() & PP_CONFIG_EDG()
#    define PP_SEQ_FOR_EACH_PRODUCT_I(r, data) PP_SEQ_FOR_EACH_PRODUCT_I_I(r, PP_TUPLE_ELEM(4, 0, data), PP_TUPLE_ELEM(4, 1, data), PP_TUPLE_ELEM(4, 2, data), PP_TUPLE_ELEM(4, 3, data))
# else
#    define PP_SEQ_FOR_EACH_PRODUCT_I(r, data) PP_SEQ_FOR_EACH_PRODUCT_I_IM(r, PP_TUPLE_REM_4 data)
#    define PP_SEQ_FOR_EACH_PRODUCT_I_IM(r, im) PP_SEQ_FOR_EACH_PRODUCT_I_I(r, im)
# endif
#
# define PP_SEQ_FOR_EACH_PRODUCT_I_I(r, cset, rset, res, macro) macro(r, PP_SEQ_TAIL(res (PP_SEQ_HEAD(cset))))
#
# if ~PP_CONFIG_FLAGS() & PP_CONFIG_MWCC()
#    define PP_SEQ_FOR_EACH_PRODUCT_H(data) PP_SEQ_FOR_EACH_PRODUCT_H_I data
# else
#    define PP_SEQ_FOR_EACH_PRODUCT_H(data) PP_SEQ_FOR_EACH_PRODUCT_H_I(PP_TUPLE_ELEM(4, 0, data), PP_TUPLE_ELEM(4, 1, data), PP_TUPLE_ELEM(4, 2, data), PP_TUPLE_ELEM(4, 3, data))
# endif
#
# define PP_SEQ_FOR_EACH_PRODUCT_H_I(cset, rset, res, macro) (PP_SEQ_HEAD(rset)(nil), PP_SEQ_TAIL(rset), res (PP_SEQ_HEAD(cset)), macro)
#
# define PP_SEQ_FOR_EACH_PRODUCT_M_0(r, data) PP_SEQ_FOR_EACH_PRODUCT_C(data, 0)(r, data)
# define PP_SEQ_FOR_EACH_PRODUCT_M_1(r, data) PP_SEQ_FOR_EACH_PRODUCT_C(data, 1)(r, data)
# define PP_SEQ_FOR_EACH_PRODUCT_M_2(r, data) PP_SEQ_FOR_EACH_PRODUCT_C(data, 2)(r, data)
# define PP_SEQ_FOR_EACH_PRODUCT_M_3(r, data) PP_SEQ_FOR_EACH_PRODUCT_C(data, 3)(r, data)
# define PP_SEQ_FOR_EACH_PRODUCT_M_4(r, data) PP_SEQ_FOR_EACH_PRODUCT_C(data, 4)(r, data)
# define PP_SEQ_FOR_EACH_PRODUCT_M_5(r, data) PP_SEQ_FOR_EACH_PRODUCT_C(data, 5)(r, data)
# define PP_SEQ_FOR_EACH_PRODUCT_M_6(r, data) PP_SEQ_FOR_EACH_PRODUCT_C(data, 6)(r, data)
# define PP_SEQ_FOR_EACH_PRODUCT_M_7(r, data) PP_SEQ_FOR_EACH_PRODUCT_C(data, 7)(r, data)
# define PP_SEQ_FOR_EACH_PRODUCT_M_8(r, data) PP_SEQ_FOR_EACH_PRODUCT_C(data, 8)(r, data)
# define PP_SEQ_FOR_EACH_PRODUCT_M_9(r, data) PP_SEQ_FOR_EACH_PRODUCT_C(data, 9)(r, data)
# define PP_SEQ_FOR_EACH_PRODUCT_M_10(r, data) PP_SEQ_FOR_EACH_PRODUCT_C(data, 10)(r, data)
# define PP_SEQ_FOR_EACH_PRODUCT_M_11(r, data) PP_SEQ_FOR_EACH_PRODUCT_C(data, 11)(r, data)
# define PP_SEQ_FOR_EACH_PRODUCT_M_12(r, data) PP_SEQ_FOR_EACH_PRODUCT_C(data, 12)(r, data)
# define PP_SEQ_FOR_EACH_PRODUCT_M_13(r, data) PP_SEQ_FOR_EACH_PRODUCT_C(data, 13)(r, data)
# define PP_SEQ_FOR_EACH_PRODUCT_M_14(r, data) PP_SEQ_FOR_EACH_PRODUCT_C(data, 14)(r, data)
# define PP_SEQ_FOR_EACH_PRODUCT_M_15(r, data) PP_SEQ_FOR_EACH_PRODUCT_C(data, 15)(r, data)
# define PP_SEQ_FOR_EACH_PRODUCT_M_16(r, data) PP_SEQ_FOR_EACH_PRODUCT_C(data, 16)(r, data)
# define PP_SEQ_FOR_EACH_PRODUCT_M_17(r, data) PP_SEQ_FOR_EACH_PRODUCT_C(data, 17)(r, data)
# define PP_SEQ_FOR_EACH_PRODUCT_M_18(r, data) PP_SEQ_FOR_EACH_PRODUCT_C(data, 18)(r, data)
# define PP_SEQ_FOR_EACH_PRODUCT_M_19(r, data) PP_SEQ_FOR_EACH_PRODUCT_C(data, 19)(r, data)
# define PP_SEQ_FOR_EACH_PRODUCT_M_20(r, data) PP_SEQ_FOR_EACH_PRODUCT_C(data, 20)(r, data)
# define PP_SEQ_FOR_EACH_PRODUCT_M_21(r, data) PP_SEQ_FOR_EACH_PRODUCT_C(data, 21)(r, data)
# define PP_SEQ_FOR_EACH_PRODUCT_M_22(r, data) PP_SEQ_FOR_EACH_PRODUCT_C(data, 22)(r, data)
# define PP_SEQ_FOR_EACH_PRODUCT_M_23(r, data) PP_SEQ_FOR_EACH_PRODUCT_C(data, 23)(r, data)
# define PP_SEQ_FOR_EACH_PRODUCT_M_24(r, data) PP_SEQ_FOR_EACH_PRODUCT_C(data, 24)(r, data)
# define PP_SEQ_FOR_EACH_PRODUCT_M_25(r, data) PP_SEQ_FOR_EACH_PRODUCT_C(data, 25)(r, data)
#
# define PP_SEQ_FOR_EACH_PRODUCT_N_0(r, data) PP_FOR_ ## r(PP_SEQ_FOR_EACH_PRODUCT_H(data), PP_SEQ_FOR_EACH_PRODUCT_P, PP_SEQ_FOR_EACH_PRODUCT_O, PP_SEQ_FOR_EACH_PRODUCT_M_1)
# define PP_SEQ_FOR_EACH_PRODUCT_N_1(r, data) PP_FOR_ ## r(PP_SEQ_FOR_EACH_PRODUCT_H(data), PP_SEQ_FOR_EACH_PRODUCT_P, PP_SEQ_FOR_EACH_PRODUCT_O, PP_SEQ_FOR_EACH_PRODUCT_M_2)
# define PP_SEQ_FOR_EACH_PRODUCT_N_2(r, data) PP_FOR_ ## r(PP_SEQ_FOR_EACH_PRODUCT_H(data), PP_SEQ_FOR_EACH_PRODUCT_P, PP_SEQ_FOR_EACH_PRODUCT_O, PP_SEQ_FOR_EACH_PRODUCT_M_3)
# define PP_SEQ_FOR_EACH_PRODUCT_N_3(r, data) PP_FOR_ ## r(PP_SEQ_FOR_EACH_PRODUCT_H(data), PP_SEQ_FOR_EACH_PRODUCT_P, PP_SEQ_FOR_EACH_PRODUCT_O, PP_SEQ_FOR_EACH_PRODUCT_M_4)
# define PP_SEQ_FOR_EACH_PRODUCT_N_4(r, data) PP_FOR_ ## r(PP_SEQ_FOR_EACH_PRODUCT_H(data), PP_SEQ_FOR_EACH_PRODUCT_P, PP_SEQ_FOR_EACH_PRODUCT_O, PP_SEQ_FOR_EACH_PRODUCT_M_5)
# define PP_SEQ_FOR_EACH_PRODUCT_N_5(r, data) PP_FOR_ ## r(PP_SEQ_FOR_EACH_PRODUCT_H(data), PP_SEQ_FOR_EACH_PRODUCT_P, PP_SEQ_FOR_EACH_PRODUCT_O, PP_SEQ_FOR_EACH_PRODUCT_M_6)
# define PP_SEQ_FOR_EACH_PRODUCT_N_6(r, data) PP_FOR_ ## r(PP_SEQ_FOR_EACH_PRODUCT_H(data), PP_SEQ_FOR_EACH_PRODUCT_P, PP_SEQ_FOR_EACH_PRODUCT_O, PP_SEQ_FOR_EACH_PRODUCT_M_7)
# define PP_SEQ_FOR_EACH_PRODUCT_N_7(r, data) PP_FOR_ ## r(PP_SEQ_FOR_EACH_PRODUCT_H(data), PP_SEQ_FOR_EACH_PRODUCT_P, PP_SEQ_FOR_EACH_PRODUCT_O, PP_SEQ_FOR_EACH_PRODUCT_M_8)
# define PP_SEQ_FOR_EACH_PRODUCT_N_8(r, data) PP_FOR_ ## r(PP_SEQ_FOR_EACH_PRODUCT_H(data), PP_SEQ_FOR_EACH_PRODUCT_P, PP_SEQ_FOR_EACH_PRODUCT_O, PP_SEQ_FOR_EACH_PRODUCT_M_9)
# define PP_SEQ_FOR_EACH_PRODUCT_N_9(r, data) PP_FOR_ ## r(PP_SEQ_FOR_EACH_PRODUCT_H(data), PP_SEQ_FOR_EACH_PRODUCT_P, PP_SEQ_FOR_EACH_PRODUCT_O, PP_SEQ_FOR_EACH_PRODUCT_M_10)
# define PP_SEQ_FOR_EACH_PRODUCT_N_10(r, data) PP_FOR_ ## r(PP_SEQ_FOR_EACH_PRODUCT_H(data), PP_SEQ_FOR_EACH_PRODUCT_P, PP_SEQ_FOR_EACH_PRODUCT_O, PP_SEQ_FOR_EACH_PRODUCT_M_11)
# define PP_SEQ_FOR_EACH_PRODUCT_N_11(r, data) PP_FOR_ ## r(PP_SEQ_FOR_EACH_PRODUCT_H(data), PP_SEQ_FOR_EACH_PRODUCT_P, PP_SEQ_FOR_EACH_PRODUCT_O, PP_SEQ_FOR_EACH_PRODUCT_M_12)
# define PP_SEQ_FOR_EACH_PRODUCT_N_12(r, data) PP_FOR_ ## r(PP_SEQ_FOR_EACH_PRODUCT_H(data), PP_SEQ_FOR_EACH_PRODUCT_P, PP_SEQ_FOR_EACH_PRODUCT_O, PP_SEQ_FOR_EACH_PRODUCT_M_13)
# define PP_SEQ_FOR_EACH_PRODUCT_N_13(r, data) PP_FOR_ ## r(PP_SEQ_FOR_EACH_PRODUCT_H(data), PP_SEQ_FOR_EACH_PRODUCT_P, PP_SEQ_FOR_EACH_PRODUCT_O, PP_SEQ_FOR_EACH_PRODUCT_M_14)
# define PP_SEQ_FOR_EACH_PRODUCT_N_14(r, data) PP_FOR_ ## r(PP_SEQ_FOR_EACH_PRODUCT_H(data), PP_SEQ_FOR_EACH_PRODUCT_P, PP_SEQ_FOR_EACH_PRODUCT_O, PP_SEQ_FOR_EACH_PRODUCT_M_15)
# define PP_SEQ_FOR_EACH_PRODUCT_N_15(r, data) PP_FOR_ ## r(PP_SEQ_FOR_EACH_PRODUCT_H(data), PP_SEQ_FOR_EACH_PRODUCT_P, PP_SEQ_FOR_EACH_PRODUCT_O, PP_SEQ_FOR_EACH_PRODUCT_M_16)
# define PP_SEQ_FOR_EACH_PRODUCT_N_16(r, data) PP_FOR_ ## r(PP_SEQ_FOR_EACH_PRODUCT_H(data), PP_SEQ_FOR_EACH_PRODUCT_P, PP_SEQ_FOR_EACH_PRODUCT_O, PP_SEQ_FOR_EACH_PRODUCT_M_17)
# define PP_SEQ_FOR_EACH_PRODUCT_N_17(r, data) PP_FOR_ ## r(PP_SEQ_FOR_EACH_PRODUCT_H(data), PP_SEQ_FOR_EACH_PRODUCT_P, PP_SEQ_FOR_EACH_PRODUCT_O, PP_SEQ_FOR_EACH_PRODUCT_M_18)
# define PP_SEQ_FOR_EACH_PRODUCT_N_18(r, data) PP_FOR_ ## r(PP_SEQ_FOR_EACH_PRODUCT_H(data), PP_SEQ_FOR_EACH_PRODUCT_P, PP_SEQ_FOR_EACH_PRODUCT_O, PP_SEQ_FOR_EACH_PRODUCT_M_19)
# define PP_SEQ_FOR_EACH_PRODUCT_N_19(r, data) PP_FOR_ ## r(PP_SEQ_FOR_EACH_PRODUCT_H(data), PP_SEQ_FOR_EACH_PRODUCT_P, PP_SEQ_FOR_EACH_PRODUCT_O, PP_SEQ_FOR_EACH_PRODUCT_M_20)
# define PP_SEQ_FOR_EACH_PRODUCT_N_20(r, data) PP_FOR_ ## r(PP_SEQ_FOR_EACH_PRODUCT_H(data), PP_SEQ_FOR_EACH_PRODUCT_P, PP_SEQ_FOR_EACH_PRODUCT_O, PP_SEQ_FOR_EACH_PRODUCT_M_21)
# define PP_SEQ_FOR_EACH_PRODUCT_N_21(r, data) PP_FOR_ ## r(PP_SEQ_FOR_EACH_PRODUCT_H(data), PP_SEQ_FOR_EACH_PRODUCT_P, PP_SEQ_FOR_EACH_PRODUCT_O, PP_SEQ_FOR_EACH_PRODUCT_M_22)
# define PP_SEQ_FOR_EACH_PRODUCT_N_22(r, data) PP_FOR_ ## r(PP_SEQ_FOR_EACH_PRODUCT_H(data), PP_SEQ_FOR_EACH_PRODUCT_P, PP_SEQ_FOR_EACH_PRODUCT_O, PP_SEQ_FOR_EACH_PRODUCT_M_23)
# define PP_SEQ_FOR_EACH_PRODUCT_N_23(r, data) PP_FOR_ ## r(PP_SEQ_FOR_EACH_PRODUCT_H(data), PP_SEQ_FOR_EACH_PRODUCT_P, PP_SEQ_FOR_EACH_PRODUCT_O, PP_SEQ_FOR_EACH_PRODUCT_M_24)
# define PP_SEQ_FOR_EACH_PRODUCT_N_24(r, data) PP_FOR_ ## r(PP_SEQ_FOR_EACH_PRODUCT_H(data), PP_SEQ_FOR_EACH_PRODUCT_P, PP_SEQ_FOR_EACH_PRODUCT_O, PP_SEQ_FOR_EACH_PRODUCT_M_25)
# define PP_SEQ_FOR_EACH_PRODUCT_N_25(r, data) PP_FOR_ ## r(PP_SEQ_FOR_EACH_PRODUCT_H(data), PP_SEQ_FOR_EACH_PRODUCT_P, PP_SEQ_FOR_EACH_PRODUCT_O, PP_SEQ_FOR_EACH_PRODUCT_M_26)
#
# endif
