# ifndef PREPROCESSOR_CONFIG_LIMITS_HPP
# define PREPROCESSOR_CONFIG_LIMITS_HPP
#
# define PP_LIMIT_MAG 256
# define PP_LIMIT_TUPLE 64
# define PP_LIMIT_DIM 3
# define PP_LIMIT_REPEAT 256
# define PP_LIMIT_WHILE 256
# define PP_LIMIT_FOR 256
# define PP_LIMIT_ITERATION 256
# define PP_LIMIT_ITERATION_DIM 3
# define PP_LIMIT_SEQ 256
# define PP_LIMIT_SLOT_SIG 10
# define PP_LIMIT_SLOT_COUNT 5
#
# endif
