#ifndef PREPROCESSOR_DETAIL_IS_BEGIN_PARENS_HPP
#define PREPROCESSOR_DETAIL_IS_BEGIN_PARENS_HPP

#if PP_VARIADICS_MSVC

#include <takisy/preprocessor/facilities/empty.hpp>

#define PP_DETAIL_VD_IBP_CAT(a, b) PP_DETAIL_VD_IBP_CAT_I(a, b)
#define PP_DETAIL_VD_IBP_CAT_I(a, b) PP_DETAIL_VD_IBP_CAT_II(a ## b)
#define PP_DETAIL_VD_IBP_CAT_II(res) res

#define PP_DETAIL_IBP_SPLIT(i, ...) \
    PP_DETAIL_VD_IBP_CAT(PP_DETAIL_IBP_PRIMITIVE_CAT(PP_DETAIL_IBP_SPLIT_,i)(__VA_ARGS__),PP_EMPTY()) \
/**/

#define PP_DETAIL_IBP_IS_VARIADIC_C(...) 1 1

#else

#define PP_DETAIL_IBP_SPLIT(i, ...) \
    PP_DETAIL_IBP_PRIMITIVE_CAT(PP_DETAIL_IBP_SPLIT_,i)(__VA_ARGS__) \
/**/

#define PP_DETAIL_IBP_IS_VARIADIC_C(...) 1

#endif /* PP_VARIADICS_MSVC */

#define PP_DETAIL_IBP_SPLIT_0(a, ...) a
#define PP_DETAIL_IBP_SPLIT_1(a, ...) __VA_ARGS__

#define PP_DETAIL_IBP_CAT(a, ...) PP_DETAIL_IBP_PRIMITIVE_CAT(a,__VA_ARGS__)
#define PP_DETAIL_IBP_PRIMITIVE_CAT(a, ...) a ## __VA_ARGS__

#define PP_DETAIL_IBP_IS_VARIADIC_R_1 1,
#define PP_DETAIL_IBP_IS_VARIADIC_R_PP_DETAIL_IBP_IS_VARIADIC_C 0,

#endif /* PREPROCESSOR_DETAIL_IS_BEGIN_PARENS_HPP */
